name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Code Quality - ShellCheck (CI)
        run: shellcheck monitor.sh

      - name: Executar 5 Testes Unitarios
        run: ./test_monitor.sh

  delivery:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Simular Deployment / Criar Artefato (CD)
        uses: actions/upload-artifact@v4
        with:
          name: script-monitoramento
          path: monitor.sh

  notificacao:
    needs: [build-and-test, delivery]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Enviar Alerta para o Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Status do Pipeline: ${{ job.status }}! Os 5 testes unitários foram validados na PR."
